
import java.awt.List;
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author benny
 */
public class Meny extends javax.swing.JFrame {

   ArrayList<Dyr> dyr = new ArrayList<Dyr>();
   ArrayList<Læreprogram> læreprogram = new ArrayList<Læreprogram>();
   final ArrayList<Rom> rom = new ArrayList<Rom>();
   Scanner scanner = new Scanner(System.in);
  
   
   
    
    
    /**
     * Creates new form Meny
     */
    public Meny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHome = new javax.swing.JPanel();
        jButtonLeggeTilRom = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelRom = new javax.swing.JPanel();
        jLabelRomNavn = new javax.swing.JLabel();
        jLabelRomNummer = new javax.swing.JLabel();
        jTextFieldRomNavn = new javax.swing.JTextField();
        jTextFieldRomNummer = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jButtonHjem = new javax.swing.JButton();
        jButtonViseRom = new javax.swing.JButton();
        jPanelDyr = new javax.swing.JPanel();
        jButtonHjem1 = new javax.swing.JButton();
        jButtonFugl = new javax.swing.JButton();
        jButtonPattedyr = new javax.swing.JButton();
        jButtonKrypdyr = new javax.swing.JButton();
        jPanelFugl = new javax.swing.JPanel();
        jPanelPattedyr = new javax.swing.JPanel();
        jPanelKrypdyr = new javax.swing.JPanel();
        jPanelRommene = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneRom = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jButtonLeggeTilRom.setText("Legge til Rom");
        jButtonLeggeTilRom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeggeTilRomActionPerformed(evt);
            }
        });

        jButton1.setText("Legge til Dyr");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLeggeTilRom, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButtonLeggeTilRom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelHome);

        jLabelRomNavn.setText("Navnet på rommet:");

        jLabelRomNummer.setText("Nummeret på rommet:");

        jTextFieldRomNavn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRomNavnActionPerformed(evt);
            }
        });

        jTextFieldRomNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRomNummerActionPerformed(evt);
            }
        });

        jButtonEnter.setText("Enter");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jButtonHjem.setText("Hjem");
        jButtonHjem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHjemActionPerformed(evt);
            }
        });

        jButtonViseRom.setText("Rommene");
        jButtonViseRom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViseRomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRomLayout = new javax.swing.GroupLayout(jPanelRom);
        jPanelRom.setLayout(jPanelRomLayout);
        jPanelRomLayout.setHorizontalGroup(
            jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRomLayout.createSequentialGroup()
                .addComponent(jButtonHjem)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelRomLayout.createSequentialGroup()
                .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRomLayout.createSequentialGroup()
                                .addComponent(jLabelRomNavn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanelRomLayout.createSequentialGroup()
                                .addComponent(jLabelRomNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldRomNummer)
                            .addComponent(jTextFieldRomNavn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRomLayout.createSequentialGroup()
                        .addComponent(jButtonViseRom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jButtonEnter)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanelRomLayout.setVerticalGroup(
            jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRomLayout.createSequentialGroup()
                .addComponent(jButtonHjem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRomNavn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRomNavn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRomNummer)
                    .addComponent(jTextFieldRomNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnter)
                    .addComponent(jButtonViseRom))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRom);

        jButtonHjem1.setText("Hjem");
        jButtonHjem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHjem1ActionPerformed(evt);
            }
        });

        jButtonFugl.setText("Legge til Fugl");
        jButtonFugl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuglActionPerformed(evt);
            }
        });

        jButtonPattedyr.setText("Legge til pattedyr");
        jButtonPattedyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPattedyrActionPerformed(evt);
            }
        });

        jButtonKrypdyr.setText("Legge til krypdyr");
        jButtonKrypdyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKrypdyrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDyrLayout = new javax.swing.GroupLayout(jPanelDyr);
        jPanelDyr.setLayout(jPanelDyrLayout);
        jPanelDyrLayout.setHorizontalGroup(
            jPanelDyrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDyrLayout.createSequentialGroup()
                .addGroup(jPanelDyrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonHjem1)
                    .addComponent(jButtonPattedyr, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jButtonKrypdyr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFugl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 412, Short.MAX_VALUE))
        );
        jPanelDyrLayout.setVerticalGroup(
            jPanelDyrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDyrLayout.createSequentialGroup()
                .addComponent(jButtonHjem1)
                .addGap(42, 42, 42)
                .addComponent(jButtonFugl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPattedyr, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonKrypdyr, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelDyr);

        javax.swing.GroupLayout jPanelFuglLayout = new javax.swing.GroupLayout(jPanelFugl);
        jPanelFugl.setLayout(jPanelFuglLayout);
        jPanelFuglLayout.setHorizontalGroup(
            jPanelFuglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jPanelFuglLayout.setVerticalGroup(
            jPanelFuglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFugl);

        javax.swing.GroupLayout jPanelPattedyrLayout = new javax.swing.GroupLayout(jPanelPattedyr);
        jPanelPattedyr.setLayout(jPanelPattedyrLayout);
        jPanelPattedyrLayout.setHorizontalGroup(
            jPanelPattedyrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jPanelPattedyrLayout.setVerticalGroup(
            jPanelPattedyrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelPattedyr);

        javax.swing.GroupLayout jPanelKrypdyrLayout = new javax.swing.GroupLayout(jPanelKrypdyr);
        jPanelKrypdyr.setLayout(jPanelKrypdyrLayout);
        jPanelKrypdyrLayout.setHorizontalGroup(
            jPanelKrypdyrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelKrypdyrLayout.setVerticalGroup(
            jPanelKrypdyrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelKrypdyr);

        jLabel1.setText("Rommene");

        jScrollPaneRom.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jScrollPaneRomComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanelRommeneLayout = new javax.swing.GroupLayout(jPanelRommene);
        jPanelRommene.setLayout(jPanelRommeneLayout);
        jPanelRommeneLayout.setHorizontalGroup(
            jPanelRommeneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRommeneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(jPanelRommeneLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jScrollPaneRom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanelRommeneLayout.setVerticalGroup(
            jPanelRommeneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRommeneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneRom, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRommene);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLeggeTilRomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeggeTilRomActionPerformed
        jPanelRom.setVisible(true);
        jPanelHome.setVisible(false);
    }//GEN-LAST:event_jButtonLeggeTilRomActionPerformed

    private void jTextFieldRomNavnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRomNavnActionPerformed
        String romNavn = scanner.nextLine();
        
    }//GEN-LAST:event_jTextFieldRomNavnActionPerformed

    private void jButtonHjemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHjemActionPerformed
        jPanelRom.setVisible(false);
        jPanelHome.setVisible(true);
    }//GEN-LAST:event_jButtonHjemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanelDyr.setVisible(true);
        jPanelHome.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonHjem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHjem1ActionPerformed
       jPanelDyr.setVisible(false);
       jPanelHome.setVisible(true);
    }//GEN-LAST:event_jButtonHjem1ActionPerformed

    private void jButtonFuglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuglActionPerformed
        jPanelDyr.setVisible(false);
        jPanelFugl.setVisible(true);
    }//GEN-LAST:event_jButtonFuglActionPerformed

    private void jButtonPattedyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPattedyrActionPerformed
        jPanelDyr.setVisible(false);
        jPanelPattedyr.setVisible(true);
    }//GEN-LAST:event_jButtonPattedyrActionPerformed

    private void jButtonKrypdyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKrypdyrActionPerformed
        jPanelDyr.setVisible(false);
        jPanelKrypdyr.setVisible(true);
    }//GEN-LAST:event_jButtonKrypdyrActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
       
      //  rom.add(jTextFieldRomNavn.getText());
      
       //rom.add(jTextFieldRomNummer.getText());
      
        int i = Integer.parseInt(jTextFieldRomNummer.getText());
        Rom rommet = new Rom();
        //rommet.add(jTextFieldRomNavn.getText());
        rommet.setRomNummer(i);
        rommet.setRomNavn(jTextFieldRomNavn.getText());
        rom.add(rommet);
        
        
        for(Rom p : rom){
            System.out.println(p.romNavn()+ p.romNummer());
        }
        
        
        
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jTextFieldRomNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRomNummerActionPerformed
        
    }//GEN-LAST:event_jTextFieldRomNummerActionPerformed

    private void jButtonViseRomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViseRomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViseRomActionPerformed

    private void jScrollPaneRomComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPaneRomComponentShown
        
    }//GEN-LAST:event_jScrollPaneRomComponentShown

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonFugl;
    private javax.swing.JButton jButtonHjem;
    private javax.swing.JButton jButtonHjem1;
    private javax.swing.JButton jButtonKrypdyr;
    private javax.swing.JButton jButtonLeggeTilRom;
    private javax.swing.JButton jButtonPattedyr;
    private javax.swing.JButton jButtonViseRom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRomNavn;
    private javax.swing.JLabel jLabelRomNummer;
    private javax.swing.JPanel jPanelDyr;
    private javax.swing.JPanel jPanelFugl;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelKrypdyr;
    private javax.swing.JPanel jPanelPattedyr;
    private javax.swing.JPanel jPanelRom;
    private javax.swing.JPanel jPanelRommene;
    private javax.swing.JScrollPane jScrollPaneRom;
    private javax.swing.JTextField jTextFieldRomNavn;
    private javax.swing.JTextField jTextFieldRomNummer;
    // End of variables declaration//GEN-END:variables
}


